---
title: "R Notebook"
output: 
---


```{r}
library(data.table)
library(tidyverse)
theme_set(theme_classic())
options(scipen=999)
library(openxlsx)
wb <- createWorkbook()
```


```{r}
merged_data <- fread('../ref/vars_events_prediction.tsv')
```


# Figure S4: plot of # SAI predictions above 0.001 per variant

```{r}
case_numbers <- unique(merged_data[variant_category == 'ours', .(curated_record_id)]) %>%
  mutate(case_number = 1:88)

preds <- fread('../ref/sai_preds_complete.csv')
preds <- unique(merged_data[, .(curated_record_id, variant_category)])[preds, on = .(curated_record_id)]
preds <- case_numbers[preds, on = .(curated_record_id)]
preds <- preds[variant_category == 'ours']

convert <- data.frame(splicing_event_class = unique(preds$splicing_event_class),
                      class_lab = c('other', 'other', 'exon skipping', 
                                    'cryptic activation', 'mis-splicing', 
                                    'intron retention', 'cryptic activation',
                                   'other', 'other'))


plotdat = preds %>% 
  left_join(convert, by = 'splicing_event_class') %>%
  filter(splicing_event_class != 'mis-splicing') %>%
  group_by(case_number,class_lab) %>%
  tally() %>% ungroup() %>% group_by(case_number) %>%
  mutate(total_preds = sum(n)) %>% arrange(total_preds) %>% 
  ungroup() %>%
  mutate(class_lab = factor(class_lab, levels = c('other', 'intron retention', 'exon skipping', 'cryptic activation'))) 

plotdat %>%
  ggplot(aes(x = factor(case_number), y = n, fill = class_lab)) +
  geom_bar(stat = 'identity', width = 0.5) +
  scale_y_continuous(breaks = seq(0,110,10), expand = c(0,1)) +
  scale_fill_manual(values = rev(c('#e84b35','#4cbbd5','#00a086', 'grey')))+
  theme(panel.grid.major.y = element_line(colour = "lightgrey", size = 0.1),
        panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = 'bottom') +
  ylab('Number of SpliceAI \u0394-scores \u2265 0.001') + xlab('Case Number') + labs(fill = '') 

ggsave('../figs/S4.pdf', height = 3, width = 13)

addWorksheet(wb, "figure_E4")
writeData(wb, "figure_E4", as.data.frame(plotdat), startRow = 1, startCol = 1)
saveWorkbook(wb, file = "../figs/source_data/source_data_extended_data_fig_4.xlsx", overwrite = TRUE)
```

```{r}
table(preds$splicing_event_class)

plotdat %>%
  filter(class_lab != 'other') %>%
  group_by(case_number) %>%
  mutate(total = sum(n)) %>% arrange(case_number) %>%
  arrange(-total)
```



